name: Web Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          pip install -r ./requirements.txt
      
      - name: Install Google Chrome
        run: |
            CHROME_VERSION="130.0.6823.1"
            CHROME_DEB="google-chrome-stable_${CHROME_VERSION}-1_amd64.deb"
            wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/${CHROME_DEB}"
            sudo dpkg -i ${CHROME_DEB} || sudo apt-get install -f 
  
      - name: Verify Google Chrome Installation
        run: |
            google-chrome --version
  
      - name: Install ChromeDriver
        run: |
            CHROME_DRIVER_VERSION="130.0.6723.91"  
            echo "Using ChromeDriver version: $CHROME_DRIVER_VERSION"
            wget "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
  
      - name: ChromeDriver Installation
        run: |
            chromedriver --version   
      
      - name: Run Robot Framework Tests
        run: |
          robot AutomationTests/Tests/web_tests.robot
